spring.application.name=Employee

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/microservices
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.hostname=localhost